runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

inbound_services:
- warmup
- mail

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 8

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /images
  static_dir: build/images
  expiration: "99d"

- url: /static
  static_dir: build/static

- url: /fonts
  static_dir: build/fonts

- url: /css
  static_dir: build/static/css

- url: /dummy
  static_dir: build/dummy

- url: /js
  static_dir: build/js

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /.*
  script: travels.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.scss$
- ^(.*/)?.*\.less$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules/.*$
- ^scripts/.*$

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
